server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
spring:
  application:
    name: cambio-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: 211191
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres?useTimezone=true&serverTimezone=UTC
    schema: cambio_service
    user: postgres
    password: 211191
    locations: classpath:db/migration
    baseline-version: 0
    out-of-order: true
springdoc:
  show-actuator: true
  api-docs:
    enabled: true
    groups:
      enabled: true
    path: /cambio/v3/api-docs
    version: OPENAPI_3_0
  swagger-ui:
    config-url: /cambio/v3/api-docs/swagger-config
    url: /cambio/v3/api-docs
management:
  tracing:
    sampling:
      probability: 1.0