server:
  port: 8100
  forward-headers-strategy: framework
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  instance:
    hostname: localhost
    prefer-ip-address: true
  retry:
    instances:
      default:
        max-attempts: 5
        wait-duration: 2s
        enable-exponential-backoff: true
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 2s
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: 211191
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres?useTimezone=true&serverTimezone=UTC
    schema: book_service
    user: postgres
    password: 211191
    locations: classpath:db/migration
    baseline-version: 0
    out-of-order: true
springdoc:
  show-actuator: true
  api-docs:
    enabled: true
    groups:
      enabled: true
    path: /book/v3/api-docs
    version: OPENAPI_3_0
  swagger-ui:
    config-url: /book/v3/api-docs/swagger-config
    url: /book/v3/api-docs


