server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: 211191
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres?useTimezone=true&serverTimezone=UTC
    schema: book_service
    user: postgres
    password: 211191
    out-of-order: true

