CREATE TABLE IF NOT EXISTS book
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    author           VARCHAR(255)                            NOT NULL,
    publication_date date                                    NOT NULL,
    price            DECIMAL(10, 2)                         NOT NULL,
    title            VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_book PRIMARY KEY (id)
);